### ISSUE TITLE
Download was not a CRX

### ISSUE THREAD

**Issue by tyssen** [kylefox/Typekit-Tweaker#5]
That's the error I get when trying to install the Chrome extension.

**Comment by kylefox** [comment]
I'm not really sure how to debug this, since it seems to install for other folks...
- Just to be certain, you installed it from the [Chrome Web Store](https://chrome.google.com/webstore/detail/typekit-tweaker/imjkefgbldfcncjipjoahpbeakfjflgf)?
- Mac / Linux / Windows?
- What version of Chrome do you have?
- Using other extensions?
- Are you signed-in to Chrome? [This article](http://www.ghacks.net/2012/12/07/fix-chrome-error-download-was-not-a-crx/) suggests maybe it's related to not being signed in.

**Comment by tyssen** [comment]
Looks like it was not being signed in that was the problem. Sorry, I've never had that error before so automatically assumed it was the extension, not the browser itself.

**Comment by kylefox** [comment]
So problem. IMO this is an issue with Chrome -- it's silly that you should be signed-in in order to install the extension, but I can't find any info about this on Google.
